# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20161027_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_creator',
            field=models.CharField(default='1', max_length=45),
            preserve_default=False,
        ),
    ]
