# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_auto_20161027_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
